spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb?useSSL=false
    username: frandioniz
    password: Patata851
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false 